name: CI
on: [push, pull_request]

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go build
      - run: |
          go fmt markut.go
          git diff --exit-code
